_wandb:
    value:
        cli_version: 0.18.3
        code_path: code/dinov2/dinov2/train/train.py
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 23
                - 24
                - 55
            "4": 3.9.19
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
